import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1778130941553 implements MigrationInterface {
    name = 'AutoMigration1778130941553'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`fk_users_ward\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`fk_admissions_admitted_by\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`fk_admissions_bed\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`fk_admissions_patient\``);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` DROP FOREIGN KEY \`fk_bed_status_logs_bed\``);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` DROP FOREIGN KEY \`fk_bed_status_logs_changed_by\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP FOREIGN KEY \`fk_beds_ward\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`fk_transfers_approved_by\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`fk_transfers_from_bed\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`fk_transfers_patient\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`fk_transfers_requested_by\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`fk_transfers_to_bed\``);
        await queryRunner.query(`DROP INDEX \`idx_patients_gender\` ON \`patients\``);
        await queryRunner.query(`DROP INDEX \`email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_users_role\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_users_ward_id\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_admissions_admitted_at\` ON \`admissions\``);
        await queryRunner.query(`DROP INDEX \`idx_admissions_admitted_by_id\` ON \`admissions\``);
        await queryRunner.query(`DROP INDEX \`idx_admissions_bed_id\` ON \`admissions\``);
        await queryRunner.query(`DROP INDEX \`idx_admissions_patient_id\` ON \`admissions\``);
        await queryRunner.query(`DROP INDEX \`idx_admissions_status\` ON \`admissions\``);
        await queryRunner.query(`DROP INDEX \`idx_bed_status_logs_bed_id\` ON \`bed_status_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_bed_status_logs_changed_by_id\` ON \`bed_status_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_bed_status_logs_created_at\` ON \`bed_status_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_bed_status_logs_status\` ON \`bed_status_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_beds_status\` ON \`beds\``);
        await queryRunner.query(`DROP INDEX \`idx_beds_ward_id\` ON \`beds\``);
        await queryRunner.query(`DROP INDEX \`uq_beds_ward_bed_number\` ON \`beds\``);
        await queryRunner.query(`DROP INDEX \`idx_wards_type\` ON \`wards\``);
        await queryRunner.query(`DROP INDEX \`name\` ON \`wards\``);
        await queryRunner.query(`DROP INDEX \`idx_transfers_approved_by_id\` ON \`transfers\``);
        await queryRunner.query(`DROP INDEX \`idx_transfers_from_bed_id\` ON \`transfers\``);
        await queryRunner.query(`DROP INDEX \`idx_transfers_patient_id\` ON \`transfers\``);
        await queryRunner.query(`DROP INDEX \`idx_transfers_requested_by_id\` ON \`transfers\``);
        await queryRunner.query(`DROP INDEX \`idx_transfers_status\` ON \`transfers\``);
        await queryRunner.query(`DROP INDEX \`idx_transfers_to_bed_id\` ON \`transfers\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`ward_id\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`patient_id\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`bed_id\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`admitted_by_id\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`ward_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`patient_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`from_bed_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`to_bed_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`requested_by_id\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`approved_by_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`wardId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`patientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`bedId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`admittedById\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`wardId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`patientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`fromBedId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`toBedId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`requestedById\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`approvedById\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`admitted_at\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`admitted_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` CHANGE \`bed_id\` \`bed_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` CHANGE \`changed_by_id\` \`changed_by_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`wards\` ADD UNIQUE INDEX \`IDX_5a722ad2f076304832fa3d80af\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`wards\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`wards\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`wards\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`wards\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`requested_at\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`requested_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_bbb0fb0fb6f6f8e936ff3b3bc9\` ON \`beds\` (\`wardId\`, \`bed_number\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_d5b5ae072248834f4b95adabdf7\` FOREIGN KEY (\`wardId\`) REFERENCES \`wards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`FK_f9d5de8d7dd020123a3c76f0a2e\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`FK_e9eac43b40763c55ca076e4d011\` FOREIGN KEY (\`bedId\`) REFERENCES \`beds\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`FK_6515e5bb9805a58aa4bba8cdd84\` FOREIGN KEY (\`admittedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` ADD CONSTRAINT \`FK_039ac2a969c02e78926031667c8\` FOREIGN KEY (\`bed_id\`) REFERENCES \`beds\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` ADD CONSTRAINT \`FK_4f0f7f06d4de66fdf8cc3ad6c48\` FOREIGN KEY (\`changed_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD CONSTRAINT \`FK_12c4b045ef8d740bb4fe8051429\` FOREIGN KEY (\`wardId\`) REFERENCES \`wards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_4b2c15e8e9c45e2f0465bc9ad83\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_a14bd6ae2274ba282629be67af2\` FOREIGN KEY (\`fromBedId\`) REFERENCES \`beds\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_fd063f9e802d99cd4f57df808b8\` FOREIGN KEY (\`toBedId\`) REFERENCES \`beds\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_430639757119b0424fd51d78f4b\` FOREIGN KEY (\`requestedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`FK_bea0014a61ad163994ef7827134\` FOREIGN KEY (\`approvedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_bea0014a61ad163994ef7827134\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_430639757119b0424fd51d78f4b\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_fd063f9e802d99cd4f57df808b8\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_a14bd6ae2274ba282629be67af2\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP FOREIGN KEY \`FK_4b2c15e8e9c45e2f0465bc9ad83\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP FOREIGN KEY \`FK_12c4b045ef8d740bb4fe8051429\``);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` DROP FOREIGN KEY \`FK_4f0f7f06d4de66fdf8cc3ad6c48\``);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` DROP FOREIGN KEY \`FK_039ac2a969c02e78926031667c8\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`FK_6515e5bb9805a58aa4bba8cdd84\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`FK_e9eac43b40763c55ca076e4d011\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`FK_f9d5de8d7dd020123a3c76f0a2e\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_d5b5ae072248834f4b95adabdf7\``);
        await queryRunner.query(`DROP INDEX \`IDX_bbb0fb0fb6f6f8e936ff3b3bc9\` ON \`beds\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`requested_at\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`requested_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wards\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`wards\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wards\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`wards\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`wards\` DROP INDEX \`IDX_5a722ad2f076304832fa3d80af\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` CHANGE \`changed_by_id\` \`changed_by_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` CHANGE \`bed_id\` \`bed_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`admitted_at\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`admitted_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`approvedById\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`requestedById\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`toBedId\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`fromBedId\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` DROP COLUMN \`patientId\``);
        await queryRunner.query(`ALTER TABLE \`beds\` DROP COLUMN \`wardId\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`admittedById\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`bedId\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP COLUMN \`patientId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`wardId\``);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`approved_by_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`requested_by_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`to_bed_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`from_bed_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD \`patient_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD \`ward_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`admitted_by_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`bed_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD \`patient_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`ward_id\` int NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_transfers_to_bed_id\` ON \`transfers\` (\`to_bed_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_transfers_status\` ON \`transfers\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_transfers_requested_by_id\` ON \`transfers\` (\`requested_by_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_transfers_patient_id\` ON \`transfers\` (\`patient_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_transfers_from_bed_id\` ON \`transfers\` (\`from_bed_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_transfers_approved_by_id\` ON \`transfers\` (\`approved_by_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`name\` ON \`wards\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_wards_type\` ON \`wards\` (\`type\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`uq_beds_ward_bed_number\` ON \`beds\` (\`ward_id\`, \`bed_number\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_beds_ward_id\` ON \`beds\` (\`ward_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_beds_status\` ON \`beds\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_bed_status_logs_status\` ON \`bed_status_logs\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_bed_status_logs_created_at\` ON \`bed_status_logs\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_bed_status_logs_changed_by_id\` ON \`bed_status_logs\` (\`changed_by_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_bed_status_logs_bed_id\` ON \`bed_status_logs\` (\`bed_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_admissions_status\` ON \`admissions\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_admissions_patient_id\` ON \`admissions\` (\`patient_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_admissions_bed_id\` ON \`admissions\` (\`bed_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_admissions_admitted_by_id\` ON \`admissions\` (\`admitted_by_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_admissions_admitted_at\` ON \`admissions\` (\`admitted_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_users_ward_id\` ON \`users\` (\`ward_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_users_role\` ON \`users\` (\`role\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_patients_gender\` ON \`patients\` (\`gender\`)`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`fk_transfers_to_bed\` FOREIGN KEY (\`to_bed_id\`) REFERENCES \`beds\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`fk_transfers_requested_by\` FOREIGN KEY (\`requested_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`fk_transfers_patient\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`fk_transfers_from_bed\` FOREIGN KEY (\`from_bed_id\`) REFERENCES \`beds\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transfers\` ADD CONSTRAINT \`fk_transfers_approved_by\` FOREIGN KEY (\`approved_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`beds\` ADD CONSTRAINT \`fk_beds_ward\` FOREIGN KEY (\`ward_id\`) REFERENCES \`wards\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` ADD CONSTRAINT \`fk_bed_status_logs_changed_by\` FOREIGN KEY (\`changed_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bed_status_logs\` ADD CONSTRAINT \`fk_bed_status_logs_bed\` FOREIGN KEY (\`bed_id\`) REFERENCES \`beds\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`fk_admissions_patient\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`fk_admissions_bed\` FOREIGN KEY (\`bed_id\`) REFERENCES \`beds\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`fk_admissions_admitted_by\` FOREIGN KEY (\`admitted_by_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`fk_users_ward\` FOREIGN KEY (\`ward_id\`) REFERENCES \`wards\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
